### ISSUE TITLE
Will support bytearray ?

### ISSUE THREAD

**Issue by tiantian1645** [hex-in/libscrc#1]
Hello:
   When i use this lib to modify raw bytes pack i found bytearry is helpful, but this package `modbus` do not support bytearry.
   Could it will be more efficient if  use bytearray?
Thank you

**Comment by hex-in** [comment]
Hello:
Thank you for your feedback.
Plan for next version support bytearray.

> Hello:
> When i use this lib to modify raw bytes pack i found bytearry is helpful, but this package `modbus` do not support bytearry.
> Could it will be more efficient if use bytearray?
> Thank you
