### ISSUE TITLE
Wheel as run-time dependency

### ISSUE THREAD

**Issue by AlexGhenno** [hex-in/libscrc#13]
Hi,
I have built a Yocto image including libscrc in it. Building the package works completely fine but an error arises when the Python pkg_resources module looks for libscrc. Wheel is listed as requirement in the libscrc package an I get this error: 

 File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel' distribution was not found and is required by libscrc

So I build libscrc on my PC without the run-time requirement specified by install_requires=['wheel'] in the setup.py file. That worked and I can import and use the library. 

Shouldn't wheel be just a build dependency instead of a run-time dependency?  

![image](https://user-images.githubusercontent.com/25311109/233705162-7d0c7b9f-03fa-46d9-bbb2-7836c7c2e806.png)

**Comment by hex-in** [comment]
Installing after building requires wheel.

**Comment by hex-in** [comment]
> Hi, I have built a Yocto image including libscrc in it. Building the package works completely fine but an error arises when the Python pkg_resources module looks for libscrc. Wheel is listed as requirement in the libscrc package an I get this error:
> 
> File "/usr/lib/python3.7/site-packages/pkg_resources/**init**.py", line 786, in resolve raise DistributionNotFound(req, requirers) pkg_resources.DistributionNotFound: The 'wheel' distribution was not found and is required by libscrc
> 
> So I build libscrc on my PC without the run-time requirement specified by install_requires=['wheel'] in the setup.py file. That worked and I can import and use the library.
> 
> Shouldn't wheel be just a build dependency instead of a run-time dependency?
> 
> ![image](https://user-images.githubusercontent.com/25311109/233705162-7d0c7b9f-03fa-46d9-bbb2-7836c7c2e806.png)


Installing after building requires wheel.
