### ISSUE TITLE
Docstring for libscrc.crc32 mentions wrong polynomial

### ISSUE THREAD

**Issue by achim1** [hex-in/libscrc#17]
The docstring for `libscrc.crc32` says the following:
```
❯ libscrc.crc32?
Docstring: Calculate CRC (WinRAR, File) of CRC32  [Poly=0xEDB88320, Init=0xFFFFFFFF, Xorout=0xFFFFFFFF Refin=True Refout=True]
Type:      builtin_function_or_method
```
However, looking into the implementation of  [`_crc32_crc32` ](https://github.com/hex-in/libscrc/blob/master/src/crc32/_crc32module.c)  it says the used polynomial is `CRC32_POLYNOMIAL_04C11DB7` which is defined as [`0x04C11DB7L`](https://github.com/hex-in/libscrc/blob/master/src/crc32/_crc32tables.h#L46).  This is for version 1.8.1.

**Comment by hex-in** [comment]
The docstring is incorrect. Thank you for your reminder.
