### ISSUE TITLE
Gradualy calculating is missed

### ISSUE THREAD

**Issue by MikhailNatalenko** [hex-in/libscrc#4]
Hi! I use this library for my auto builds. It checks my firmware's crc (quite a big file), and I can't calculate it without gradual calculating. Could you get this feature back?

**Comment by fglaria** [comment]
Same problem.
I need to check the CRC of a really large sequence, and it won't fit on any byte array.

**Comment by hex-in** [comment]
> Hi! I use this library for my auto builds. It checks my firmware's crc (quite a big file), and I can't calculate it without gradual calculating. Could you get this feature back?

Ok no problem, I will recover as soon as possible.

**Comment by hex-in** [comment]
> Same problem.
> I need to check the CRC of a really large sequence, and it won't fit on any byte array.

Ok I got. Thanks for your feedback.

**Comment by hex-in** [comment]
Release v1.5 fixed #4

**Comment by MikhailNatalenko** [comment]
Thank you very much! I'll check it later
