### ISSUE TITLE
Cannot install libscrc in Python 2.7 x64

### ISSUE THREAD

**Issue by bslava** [hex-in/libscrc#6]
Hello Heyn,

Thanks for the great library!

We mostly use Python 3.x, however we have to support backward compatibility with Python 2.7. When I try to install libscrc under Python 2.7 x64 I receive an error message: 
![image](https://user-images.githubusercontent.com/13033593/98354990-38e24400-202a-11eb-9e05-15ff55dcfa00.png)

Could you please explain the reason for that?

Regards,
Slava

**Comment by hex-in** [comment]
Thank you for your attention, it will be resolved soon.

**Comment by hex-in** [comment]
> Hello Heyn,
> 
> Thanks for the great library!
> 
> We mostly use Python 3.x, however we have to support backward compatibility with Python 2.7. When I try to install libscrc under Python 2.7 x64 I receive an error message:
> ![image](https://user-images.githubusercontent.com/13033593/98354990-38e24400-202a-11eb-9e05-15ff55dcfa00.png)
> 
> Could you please explain the reason for that?
> 
> Regards,
> Slava

Thank you for your attention, it will be resolved soon

**Comment by hex-in** [comment]
I have fixed the problem, please try again.

**Comment by bslava** [comment]
Thanks a lot!
